package material

import gregtech.api.unification.material.info.MaterialIconType
import gregtech.api.unification.ore.OrePrefix
import gregtech.api.unification.stack.MaterialStack

import gregtech.common.items.MetaItems

import materials.GTHHMaterials

import material.GTHHMaterialIconType

import static gregtech.api.unification.material.Materials.*

class GTHHOrePrefix {

    static OrePrefix oreMoon = new OrePrefix("oreMoon", -1, null, MaterialIconType.ore, OrePrefix.Flags.ENABLE_UNIFICATION, OrePrefix.Conditions.hasOreProperty)
    static OrePrefix oreCeres = new OrePrefix("oreCeres", -1, null, MaterialIconType.ore, OrePrefix.Flags.ENABLE_UNIFICATION, OrePrefix.Conditions.hasOreProperty)
    static OrePrefix orePluto = new OrePrefix("orePluto", -1, null, MaterialIconType.ore, OrePrefix.Flags.ENABLE_UNIFICATION, OrePrefix.Conditions.hasOreProperty)

    static OrePrefix cluster = new OrePrefix("cluster", -1, null, GTHHMaterialIconType.cluster, OrePrefix.Flags.ENABLE_UNIFICATION, OrePrefix.Conditions.hasOreProperty)
    static OrePrefix glob = new OrePrefix("glob", -1, null, GTHHMaterialIconType.glob, OrePrefix.Flags.ENABLE_UNIFICATION, OrePrefix.Conditions.hasOreProperty)
    static OrePrefix fragment = new OrePrefix("fragment", -1, null, GTHHMaterialIconType.fragment, OrePrefix.Flags.ENABLE_UNIFICATION, OrePrefix.Conditions.hasOreProperty)
    static OrePrefix murky = new OrePrefix("murky", -1, null, GTHHMaterialIconType.murky, OrePrefix.Flags.ENABLE_UNIFICATION, OrePrefix.Conditions.hasOreProperty)

    static void init() {

        OrePrefix orePrefixDust = OrePrefix.getPrefix("dust")
        OrePrefix orePrefixDustSmall = OrePrefix.getPrefix("dustSmall")
        OrePrefix orePrefixDustTiny = OrePrefix.getPrefix("dustTiny")
        OrePrefix orePrefixIngot = OrePrefix.getPrefix("ingot")
        OrePrefix orePrefixIngotHot = OrePrefix.getPrefix("ingotHot")
        OrePrefix orePrefixDustImpure = OrePrefix.getPrefix("dustImpure")
        OrePrefix orePrefixDustPure = OrePrefix.getPrefix("dustPure")
        OrePrefix orePrefixCrushed = OrePrefix.getPrefix("crushed")
        OrePrefix orePrefixCrushedPurified = OrePrefix.getPrefix("crushedPurified")
        OrePrefix orePrefixCrushedCentrifuged = OrePrefix.getPrefix("crushedCentrifuged")
        OrePrefix orePrefixPlate = OrePrefix.getPrefix("plate")
        OrePrefix orePrefixPlateDouble = OrePrefix.getPrefix("plateDouble")
        OrePrefix orePrefixPlateDense = OrePrefix.getPrefix("plateDense")
        OrePrefix orePrefixFoil = OrePrefix.getPrefix("foil")
        OrePrefix orePrefixStick = OrePrefix.getPrefix("stick")
        OrePrefix orePrefixStickLong = OrePrefix.getPrefix("stickLong")
        OrePrefix orePrefixBolt = OrePrefix.getPrefix("bolt")
        OrePrefix orePrefixScrew = OrePrefix.getPrefix("screw")
        OrePrefix orePrefixNugget = OrePrefix.getPrefix("nugget")
        OrePrefix orePrefixRing = OrePrefix.getPrefix("ring")
        OrePrefix orePrefixRound = OrePrefix.getPrefix("round")
        OrePrefix orePrefixSpring = OrePrefix.getPrefix("spring")
        OrePrefix orePrefixSpringSmall = OrePrefix.getPrefix("springSmall")
        OrePrefix orePrefixGear = OrePrefix.getPrefix("gear")
        OrePrefix orePrefixGearSmall = OrePrefix.getPrefix("gearSmall")
        OrePrefix orePrefixWireFine = OrePrefix.getPrefix("wireFine")
        OrePrefix orePrefixRotor = OrePrefix.getPrefix("rotor")
        OrePrefix orePrefixLens = OrePrefix.getPrefix("lens")
        OrePrefix orePrefixCluster = OrePrefix.getPrefix("cluster")
        OrePrefix orePrefixGlob = OrePrefix.getPrefix("glob")
        OrePrefix orePrefixFragment = OrePrefix.getPrefix("fragment")
        OrePrefix orePrefixMurky = OrePrefix.getPrefix("murky")
        OrePrefix orePrefixBlock = OrePrefix.getPrefix("block")

        //Cosmic Neutronium
        orePrefixDust.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixDustSmall.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixDustTiny.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixIngot.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixIngotHot.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixDustImpure.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixDustPure.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixCrushed.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixCrushedPurified.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixCrushedCentrifuged.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixPlate.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixPlateDouble.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixPlateDense.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixFoil.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixStick.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixStickLong.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixBolt.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixScrew.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixNugget.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixRing.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixRound.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixSpring.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixSpringSmall.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixGear.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixGearSmall.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixWireFine.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixRotor.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixLens.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixCluster.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixGlob.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixFragment.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixMurky.setIgnored(GTHHMaterials.CosmicNeutronium)
        orePrefixBlock.setIgnored(GTHHMaterials.CosmicNeutronium)

        //Infinity
        orePrefixDust.setIgnored(GTHHMaterials.Infinity)
        orePrefixDustSmall.setIgnored(GTHHMaterials.Infinity)
        orePrefixDustTiny.setIgnored(GTHHMaterials.Infinity)
        orePrefixIngot.setIgnored(GTHHMaterials.Infinity)
        orePrefixIngotHot.setIgnored(GTHHMaterials.Infinity)
        orePrefixDustImpure.setIgnored(GTHHMaterials.Infinity)
        orePrefixDustPure.setIgnored(GTHHMaterials.Infinity)
        orePrefixCrushed.setIgnored(GTHHMaterials.Infinity)
        orePrefixCrushedPurified.setIgnored(GTHHMaterials.Infinity)
        orePrefixCrushedCentrifuged.setIgnored(GTHHMaterials.Infinity)
        orePrefixPlate.setIgnored(GTHHMaterials.Infinity)
        orePrefixPlateDouble.setIgnored(GTHHMaterials.Infinity)
        orePrefixPlateDense.setIgnored(GTHHMaterials.Infinity)
        orePrefixFoil.setIgnored(GTHHMaterials.Infinity)
        orePrefixStick.setIgnored(GTHHMaterials.Infinity)
        orePrefixStickLong.setIgnored(GTHHMaterials.Infinity)
        orePrefixBolt.setIgnored(GTHHMaterials.Infinity)
        orePrefixScrew.setIgnored(GTHHMaterials.Infinity)
        orePrefixNugget.setIgnored(GTHHMaterials.Infinity)
        orePrefixRing.setIgnored(GTHHMaterials.Infinity)
        orePrefixRound.setIgnored(GTHHMaterials.Infinity)
        orePrefixSpring.setIgnored(GTHHMaterials.Infinity)
        orePrefixSpringSmall.setIgnored(GTHHMaterials.Infinity)
        orePrefixGear.setIgnored(GTHHMaterials.Infinity)
        orePrefixGearSmall.setIgnored(GTHHMaterials.Infinity)
        orePrefixWireFine.setIgnored(GTHHMaterials.Infinity)
        orePrefixRotor.setIgnored(GTHHMaterials.Infinity)
        orePrefixLens.setIgnored(GTHHMaterials.Infinity)
        orePrefixCluster.setIgnored(GTHHMaterials.Infinity)
        orePrefixGlob.setIgnored(GTHHMaterials.Infinity)
        orePrefixFragment.setIgnored(GTHHMaterials.Infinity)
        orePrefixMurky.setIgnored(GTHHMaterials.Infinity)
        orePrefixBlock.setIgnored(GTHHMaterials.Infinity)


        //Multiversium 
        orePrefixDust.setIgnored(GTHHMaterials.Multiversium)
        orePrefixDustSmall.setIgnored(GTHHMaterials.Multiversium)
        orePrefixDustTiny.setIgnored(GTHHMaterials.Multiversium)
        orePrefixIngot.setIgnored(GTHHMaterials.Multiversium)
        orePrefixIngotHot.setIgnored(GTHHMaterials.Multiversium)
        orePrefixDustImpure.setIgnored(GTHHMaterials.Multiversium)
        orePrefixDustPure.setIgnored(GTHHMaterials.Multiversium)
        orePrefixCrushed.setIgnored(GTHHMaterials.Multiversium)
        orePrefixCrushedPurified.setIgnored(GTHHMaterials.Multiversium)
        orePrefixCrushedCentrifuged.setIgnored(GTHHMaterials.Multiversium)
        orePrefixPlate.setIgnored(GTHHMaterials.Multiversium)
        orePrefixPlateDouble.setIgnored(GTHHMaterials.Multiversium)
        orePrefixPlateDense.setIgnored(GTHHMaterials.Multiversium)
        orePrefixFoil.setIgnored(GTHHMaterials.Multiversium)
        orePrefixStick.setIgnored(GTHHMaterials.Multiversium)
        orePrefixStickLong.setIgnored(GTHHMaterials.Multiversium)
        orePrefixBolt.setIgnored(GTHHMaterials.Multiversium)
        orePrefixScrew.setIgnored(GTHHMaterials.Multiversium)
        orePrefixNugget.setIgnored(GTHHMaterials.Multiversium)
        orePrefixRing.setIgnored(GTHHMaterials.Multiversium)
        orePrefixRound.setIgnored(GTHHMaterials.Multiversium)
        orePrefixSpring.setIgnored(GTHHMaterials.Multiversium)
        orePrefixSpringSmall.setIgnored(GTHHMaterials.Multiversium)
        orePrefixGear.setIgnored(GTHHMaterials.Multiversium)
        orePrefixGearSmall.setIgnored(GTHHMaterials.Multiversium)
        orePrefixWireFine.setIgnored(GTHHMaterials.Multiversium)
        orePrefixRotor.setIgnored(GTHHMaterials.Multiversium)
        orePrefixLens.setIgnored(GTHHMaterials.Multiversium)
        orePrefixCluster.setIgnored(GTHHMaterials.Multiversium)
        orePrefixGlob.setIgnored(GTHHMaterials.Multiversium)
        orePrefixFragment.setIgnored(GTHHMaterials.Multiversium)
        orePrefixMurky.setIgnored(GTHHMaterials.Multiversium)
        
        //Borosilicate Glass
        orePrefixPlate.removeIgnored(BorosilicateGlass)

        orePrefixIngot.setIgnored(GTHHMaterials.ElectricalSteel)
        orePrefixIngot.setIgnored(GTHHMaterials.EnergeticAlloy)
        orePrefixIngot.setIgnored(GTHHMaterials.VibrantAlloy)
        orePrefixIngot.setIgnored(GTHHMaterials.RedstoneAlloy)
        orePrefixIngot.setIgnored(GTHHMaterials.ConductiveIron)
        orePrefixIngot.setIgnored(GTHHMaterials.PulsatingIron)
        orePrefixIngot.setIgnored(GTHHMaterials.DarkSteel)
        orePrefixIngot.setIgnored(GTHHMaterials.Soularium)
        orePrefixIngot.setIgnored(GTHHMaterials.EndSteel)
        orePrefixIngot.setIgnored(GTHHMaterials.CrudeSteel)
        orePrefixIngot.setIgnored(GTHHMaterials.CrystallineAlloy)
        orePrefixIngot.setIgnored(GTHHMaterials.MelodicAlloy)
        orePrefixIngot.setIgnored(GTHHMaterials.CrystallinePinkSlime)
        orePrefixIngot.setIgnored(GTHHMaterials.EnergeticSilver)
        orePrefixIngot.setIgnored(GTHHMaterials.VividAlloy)
        orePrefixIngot.setIgnored(GTHHMaterials.StellarAlloy)
        orePrefixIngot.setIgnored(GTHHMaterials.Infinity)

        orePrefixNugget.setIgnored(GTHHMaterials.ElectricalSteel)
        orePrefixNugget.setIgnored(GTHHMaterials.EnergeticAlloy)
        orePrefixNugget.setIgnored(GTHHMaterials.VibrantAlloy)
        orePrefixNugget.setIgnored(GTHHMaterials.RedstoneAlloy)
        orePrefixNugget.setIgnored(GTHHMaterials.ConductiveIron)
        orePrefixNugget.setIgnored(GTHHMaterials.PulsatingIron)
        orePrefixNugget.setIgnored(GTHHMaterials.DarkSteel)
        orePrefixNugget.setIgnored(GTHHMaterials.Soularium)
        orePrefixNugget.setIgnored(GTHHMaterials.EndSteel)
        orePrefixNugget.setIgnored(GTHHMaterials.CrudeSteel)
        orePrefixNugget.setIgnored(GTHHMaterials.CrystallineAlloy)
        orePrefixNugget.setIgnored(GTHHMaterials.MelodicAlloy)
        orePrefixNugget.setIgnored(GTHHMaterials.CrystallinePinkSlime)
        orePrefixNugget.setIgnored(GTHHMaterials.EnergeticSilver)
        orePrefixNugget.setIgnored(GTHHMaterials.VividAlloy)
        orePrefixNugget.setIgnored(GTHHMaterials.ElectricalSteel)
        orePrefixNugget.setIgnored(GTHHMaterials.StellarAlloy)

        orePrefixBlock.setIgnored(GTHHMaterials.ElectricalSteel)
        orePrefixBlock.setIgnored(GTHHMaterials.EnergeticAlloy)
        orePrefixBlock.setIgnored(GTHHMaterials.VibrantAlloy)
        orePrefixBlock.setIgnored(GTHHMaterials.RedstoneAlloy)
        orePrefixBlock.setIgnored(GTHHMaterials.ConductiveIron)
        orePrefixBlock.setIgnored(GTHHMaterials.PulsatingIron)
        orePrefixBlock.setIgnored(GTHHMaterials.DarkSteel)
        orePrefixBlock.setIgnored(GTHHMaterials.Soularium)
        orePrefixBlock.setIgnored(GTHHMaterials.EndSteel)
        orePrefixBlock.setIgnored(GTHHMaterials.CrudeSteel)
        orePrefixBlock.setIgnored(GTHHMaterials.CrystallineAlloy)
        orePrefixBlock.setIgnored(GTHHMaterials.MelodicAlloy)
        orePrefixBlock.setIgnored(GTHHMaterials.CrystallinePinkSlime)
        orePrefixBlock.setIgnored(GTHHMaterials.EnergeticSilver)
        orePrefixBlock.setIgnored(GTHHMaterials.VividAlloy)
        orePrefixBlock.setIgnored(GTHHMaterials.StellarAlloy)
        orePrefixBlock.setIgnored(GTHHMaterials.Infinity)

        orePrefixDust.setIgnored(GTHHMaterials.Soularium)

        oreMoon.addSecondaryMaterial(new MaterialStack(GTHHMaterials.Moon, OrePrefix.dust.materialAmount))
        oreCeres.addSecondaryMaterial(new MaterialStack(GTHHMaterials.Ceres, OrePrefix.dust.materialAmount))
        orePluto.addSecondaryMaterial(new MaterialStack(GTHHMaterials.Pluto, OrePrefix.dust.materialAmount))

        MetaItems.addOrePrefix(GTHHOrePrefix.cluster)
        MetaItems.addOrePrefix(GTHHOrePrefix.glob)
        MetaItems.addOrePrefix(GTHHOrePrefix.fragment)
        MetaItems.addOrePrefix(GTHHOrePrefix.murky)

    }
}
