recipemap('mixer').recipeBuilder()
    .inputs(metaitem('dustMica') * 6, metaitem('dustAsbestos') * 4, metaitem('rubber_drop') * 6)
    .outputs(metaitem('component.mica_based_pulp') * 16)
    .duration(200)
    .EUt(24)
    .buildAndRegister()

recipemap('forming_press').recipeBuilder()
    .notConsumable(metaitem('shape.mold.plate') * 1)
    .inputs(metaitem('component.mica_based_pulp') * 4)
    .outputs(metaitem('component.mica_based_sheet') * 1)
    .duration(200)
    .EUt(24)
    .buildAndRegister()

recipemap('alloy_smelter').recipeBuilder()
    .inputs(metaitem('component.mica_based_sheet') * 1, ore('dustSiliconDioxide') * 4)
    .outputs(metaitem('component.mica_insulator_sheet') * 1)
    .duration(200)
    .EUt(24)
    .buildAndRegister()

recipemap('bender').recipeBuilder()
    .inputs(metaitem('component.mica_insulator_sheet') * 1)
    .outputs(metaitem('component.mica_insulator_foil') * 4)
    .circuitMeta(1)
    .duration(200)
    .EUt(24)
    .buildAndRegister()