
def hiddenItems = [
    item('enderio:item_alloy_endergy_ball'),
    item('enderio:item_alloy_endergy_ball', 1),
    item('enderio:item_alloy_endergy_ball', 2),
    item('enderio:item_alloy_endergy_ball', 3),
    item('enderio:item_alloy_endergy_ball', 4),
    item('enderio:item_alloy_endergy_ball', 5),
    item('enderio:item_alloy_endergy_ball', 6),
    item('enderio:block_alloy', 9),
    item('enderio:item_alloy_nugget', 9),
    item('enderio:item_alloy_ingot', 9),
    item('enderio:item_alloy_ball'),
    item('enderio:item_alloy_ball', 1),
    item('enderio:item_alloy_ball', 2),
    item('enderio:item_alloy_ball', 3),
    item('enderio:item_alloy_ball', 4),
    item('enderio:item_alloy_ball', 5),
    item('enderio:item_alloy_ball', 8),
    item('enderio:item_alloy_ball', 9),
    item('enderio:item_material', 9),
    item('enderio:item_material', 10),
    item('enderio:item_material', 21),
    item('enderio:item_material', 23),
    item('enderio:item_material', 24),
    item('enderio:item_material', 25),
    item('enderio:item_material', 26),
    item('enderio:item_material', 27),
    item('enderio:item_material', 28),
    item('enderio:item_material', 29),
    item('enderio:item_material', 32),
    item('enderio:item_material', 33),
    item('enderio:item_material', 46),
    item('enderio:item_material', 47),
    item('enderio:item_material', 72),
    item('enderio:item_material', 5),
    item('enderio:item_power_conduit'),
    item('enderio:item_power_conduit', 1),
    item('enderio:item_power_conduit', 2),
    item('enderio:block_simple_furnace'),
    item('enderio:block_simple_alloy_smelter'),
    item('enderio:block_alloy_smelter'),
    item('enderio:block_enhanced_alloy_smelter'),
    item('enderio:block_combustion_generator'),
    item('enderio:block_enhanced_combustion_generator'),
    item('enderio:block_simple_stirling_generator'),
    item('enderio:block_stirling_generator'),
    item('enderio:block_zombie_generator'),
    item('enderio:block_franken_zombie_generator'),
    item('enderio:block_ender_generator'),
    item('enderio:block_lava_generator'),
    item('enderio:block_simple_sag_mill'),
    item('enderio:block_sag_mill'),
    item('enderio:block_enhanced_sag_mill')
]

mods.jei.ingredient.removeAndHide(hiddenItems)
