log.infoMC("Changing Logipipes Component Recipes..")
//Sand Compound Boule
recipemap('electric_blast_furnace').recipeBuilder()
    .inputs(metaitem('dustSandCompound') * 32, metaitem('dustTinyGalliumArsenide') * 1)
    .outputs(metaitem('boule.sand_compound') * 1)
    .circuitMeta(1)
    .blastFurnaceTemp(1700)
    .duration(4500)
    .EUt(96)
    .buildAndRegister()

//Sand Compound Wafer
recipemap('cutter').recipeBuilder()
    .inputs(metaitem('boule.sand_compound') * 1)
    .outputs(metaitem('wafer.sand_compound') * 32, metaitem('dustSandCompound') * 4)
    .fluidInputs(fluid('water') * 200)
    .duration(600)
    .EUt(64)
    .buildAndRegister()

recipemap('cutter').recipeBuilder()
    .inputs(metaitem('boule.sand_compound') * 1)
    .outputs(metaitem('wafer.sand_compound') * 32, metaitem('dustSandCompound') * 4)
    .fluidInputs(fluid('distilled_water') * 100)
    .duration(500)
    .EUt(64)
    .buildAndRegister()

recipemap('cutter').recipeBuilder()
    .inputs(metaitem('boule.sand_compound') * 1)
    .outputs(metaitem('wafer.sand_compound') * 32, metaitem('dustSandCompound') * 4)
    .fluidInputs(fluid('lubricant') * 50)
    .duration(400)
    .EUt(64)
    .buildAndRegister()

//Basic Chip Wafer
recipemap('chemical_reactor').recipeBuilder()
    .inputs(metaitem('wafer.sand_compound') * 1, metaitem('wireFineCopper') * 32)
    .outputs(metaitem('wafer.basic_chip') * 1)
    .fluidInputs(fluid('soldering_alloy') * 576)
    .duration(1200)
    .EUt(64)
    .buildAndRegister()

//Advanced Chip Wafer
recipemap('chemical_reactor').recipeBuilder()
    .inputs(metaitem('wafer.sand_compound') * 1, metaitem('wireFineBlueAlloy') * 32)
    .outputs(metaitem('wafer.advanced_chip') * 1)
    .fluidInputs(fluid('soldering_alloy') * 576)
    .duration(1200)
    .EUt(64)
    .buildAndRegister()

//FPGA Wafer
recipemap('chemical_reactor').recipeBuilder()
    .inputs(metaitem('wafer.sand_compound') * 1, metaitem('wireFineRoseGold') * 32)
    .outputs(metaitem('wafer.fpga') * 1)
    .fluidInputs(fluid('soldering_alloy') * 576)
    .duration(1200)
    .EUt(64)
    .buildAndRegister()

//Raw Basic Chip
crafting.removeByOutput(item('logisticspipes:chip_basic_raw'))
recipemap('cutter').recipeBuilder()
    .inputs(metaitem('wafer.basic_chip') * 1)
    .outputs(item('logisticspipes:chip_basic_raw') * 16)
    .fluidInputs(fluid('water') * 250)
    .duration(600)
    .EUt(64)
    .buildAndRegister()

recipemap('cutter').recipeBuilder()
    .inputs(metaitem('wafer.basic_chip') * 1)
    .outputs(item('logisticspipes:chip_basic_raw') * 16)
    .fluidInputs(fluid('distilled_water') * 100)
    .duration(500)
    .EUt(64)
    .buildAndRegister()

recipemap('cutter').recipeBuilder()
    .inputs(metaitem('wafer.basic_chip') * 1)
    .outputs(item('logisticspipes:chip_basic_raw') * 16)
    .fluidInputs(fluid('lubricant') * 50)
    .duration(400)
    .EUt(64)
    .buildAndRegister()

//Raw Advanced Chip
crafting.removeByOutput(item('logisticspipes:chip_advanced_raw'))
recipemap('cutter').recipeBuilder()
    .inputs(metaitem('wafer.advanced_chip') * 1)
    .outputs(item('logisticspipes:chip_advanced_raw') * 16)
    .fluidInputs(fluid('water') * 250)
    .duration(600)
    .EUt(64)
    .buildAndRegister()

recipemap('cutter').recipeBuilder()
    .inputs(metaitem('wafer.advanced_chip') * 1)
    .outputs(item('logisticspipes:chip_advanced_raw') * 16)
    .fluidInputs(fluid('distilled_water') * 100)
    .duration(500)
    .EUt(64)
    .buildAndRegister()

recipemap('cutter').recipeBuilder()
    .inputs(metaitem('wafer.advanced_chip') * 1)
    .outputs(item('logisticspipes:chip_advanced_raw') * 16)
    .fluidInputs(fluid('lubricant') * 50)
    .duration(400)
    .EUt(64)
    .buildAndRegister()

//Raw FPGA
crafting.removeByOutput(item('logisticspipes:chip_fpga_raw'))
recipemap('cutter').recipeBuilder()
    .inputs(metaitem('wafer.fpga') * 1)
    .outputs(item('logisticspipes:chip_fpga_raw')* 16)
    .fluidInputs(fluid('water') * 250)
    .duration(600)
    .EUt(64)
    .buildAndRegister()

recipemap('cutter').recipeBuilder()
    .inputs(metaitem('wafer.fpga') * 1)
    .outputs(item('logisticspipes:chip_fpga_raw') * 16)
    .fluidInputs(fluid('distilled_water') * 100)
    .duration(500)
    .EUt(64)
    .buildAndRegister()

recipemap('cutter').recipeBuilder()
    .inputs(metaitem('wafer.fpga') * 1)
    .outputs(item('logisticspipes:chip_fpga_raw') * 16)
    .fluidInputs(fluid('lubricant') * 50)
    .duration(400)
    .EUt(64)
    .buildAndRegister()

//Basic Chip
furnace.removeByInput(item('logisticspipes:chip_basic_raw'))
recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.resistor') * 8, metaitem('component.diode') * 4, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_basic_raw') * 1, metaitem('board.phenolic') * 1)
    .outputs(item('logisticspipes:chip_basic') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(600)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.smd.resistor') * 6, metaitem('component.smd.diode') * 3, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_basic_raw') * 1, metaitem('board.plastic'))
    .outputs(item('logisticspipes:chip_basic') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(550)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.nano.smd.resistor') * 4, metaitem('component.nano.smd.diode') * 2, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_basic_raw') * 1, metaitem('board.epoxy'))
    .outputs(item('logisticspipes:chip_basic') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(500)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.quantum.smd.resistor') * 2, metaitem('component.quantum.smd.diode') * 1, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_basic_raw') * 1, metaitem('board.fiber_reinforced'))
    .outputs(item('logisticspipes:chip_basic') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(450)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.crystalline.smd.resistor') * 1, metaitem('component.crystalline.smd.diode') * 1, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_basic_raw') * 1, metaitem('board.multilayer.fiber_reinforced'))
    .outputs(item('logisticspipes:chip_basic') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(400)
    .EUt(64)
    .buildAndRegister()

//Advanced Chip
furnace.removeByInput(item('logisticspipes:chip_advanced_raw'))
recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltBlueAlloy') * 8, metaitem('component.resistor') * 8, metaitem('component.diode') * 4, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_advanced_raw') * 1, metaitem('board.phenolic') * 1)
    .outputs(item('logisticspipes:chip_advanced') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(400)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.smd.resistor') * 6, metaitem('component.smd.diode') * 3, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_advanced_raw') * 1, metaitem('board.plastic'))
    .outputs(item('logisticspipes:chip_advanced') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(550)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.nano.smd.resistor') * 4, metaitem('component.nano.smd.diode') * 2, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_advanced_raw') * 1, metaitem('board.epoxy'))
    .outputs(item('logisticspipes:chip_advanced') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(500)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.quantum.smd.resistor') * 2, metaitem('component.quantum.smd.diode') * 1, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_advanced_raw') * 1, metaitem('board.fiber_reinforced'))
    .outputs(item('logisticspipes:chip_advanced') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(450)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.crystalline.smd.resistor') * 1, metaitem('component.crystalline.smd.diode') * 1, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_advanced_raw') * 1, metaitem('board.multilayer.fiber_reinforced'))
    .outputs(item('logisticspipes:chip_advanced') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(400)
    .EUt(64)
    .buildAndRegister()

//FPGA
furnace.removeByInput(item('logisticspipes:chip_fpga_raw'))
recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltRedAlloy') * 8, metaitem('component.resistor') * 8, metaitem('component.diode') * 4, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_fpga_raw') * 1, metaitem('board.phenolic') * 1)
    .outputs(item('logisticspipes:chip_fpga') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(400)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.smd.resistor') * 6, metaitem('component.smd.diode') * 3, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_fpga_raw') * 1, metaitem('board.plastic'))
    .outputs(item('logisticspipes:chip_fpga') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(550)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.nano.smd.resistor') * 4, metaitem('component.nano.smd.diode') * 2, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_fpga_raw') * 1, metaitem('board.epoxy'))
    .outputs(item('logisticspipes:chip_fpga') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(500)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.quantum.smd.resistor') * 2, metaitem('component.quantum.smd.diode') * 1, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_fpga_raw') * 1, metaitem('board.fiber_reinforced'))
    .outputs(item('logisticspipes:chip_fpga') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(450)
    .EUt(64)
    .buildAndRegister()

recipemap('circuit_assembler').recipeBuilder()
    .inputs(metaitem('boltSteel') * 8, metaitem('component.crystalline.smd.resistor') * 1, metaitem('component.crystalline.smd.diode') * 1, metaitem('plate.simple_system_on_chip') * 1, item('logisticspipes:chip_fpga_raw') * 1, metaitem('board.multilayer.fiber_reinforced'))
    .outputs(item('logisticspipes:chip_fpga') * 1)
    .fluidInputs(fluid('soldering_alloy') * 72)
    .duration(400)
    .EUt(64)
    .buildAndRegister()