//Nuclear Craft
mods.jei.category.hideCategory('nuclearcraft_collector')
mods.jei.category.hideCategory('nuclearcraft_decay_generator')
mods.jei.category.hideCategory('nuclearcraft_manufactory')
mods.jei.category.hideCategory('nuclearcraft_separator')
mods.jei.category.hideCategory('nuclearcraft_decay_hastener')
mods.jei.category.hideCategory('nuclearcraft_fuel_reprocessor')
mods.jei.category.hideCategory('nuclearcraft_alloy_furnace')
mods.jei.category.hideCategory('nuclearcraft_infuser')
mods.jei.category.hideCategory('nuclearcraft_melter')
mods.jei.category.hideCategory('nuclearcraft_supercooler')
mods.jei.category.hideCategory('nuclearcraft_electrolyzer')
mods.jei.category.hideCategory('nuclearcraft_assembler')
mods.jei.category.hideCategory('nuclearcraft_ingot_former')
mods.jei.category.hideCategory('nuclearcraft_pressurizer')
mods.jei.category.hideCategory('nuclearcraft_chemical_reactor')
mods.jei.category.hideCategory('nuclearcraft_salt_mixer')
mods.jei.category.hideCategory('nuclearcraft_crystallizer')
mods.jei.category.hideCategory('nuclearcraft_enricher')
mods.jei.category.hideCategory('nuclearcraft_extractor')
mods.jei.category.hideCategory('nuclearcraft_centrifuge')
mods.jei.category.hideCategory('nuclearcraft_rock_crusher')
mods.jei.category.hideCategory('nuclearcraft_electric_furnace')
mods.jei.category.hideCategory('nuclearcraft_turbine')

//QMD
mods.jei.category.hideCategory('mass_spectrometer')

//mods.jei.category.hideCategory('')