mods.thaumcraft.crucible.removeByOutput(item('thaumcraft:cluster'))
mods.thaumcraft.crucible.removeByOutput(item('thaumcraft:cluster', 1))
mods.thaumcraft.crucible.removeByOutput(item('thaumcraft:cluster', 2))
mods.thaumcraft.crucible.removeByOutput(item('thaumcraft:cluster', 3))
mods.thaumcraft.crucible.removeByOutput(item('thaumcraft:cluster', 6))
mods.thaumcraft.crucible.removeByOutput(item('tc_integration:cluster_aluminum'))
mods.thaumcraft.crucible.removeByOutput(item('tc_integration:cluster_astralstarmetal'))

mods.thaumcraft.crucible.recipeBuilder()
    .researchKey('METALPURIFICATION')
    .catalyst(ore('stickWood'))
    .output(metaitem('catalyst.native'))
    .aspect(aspect('metallum') * 5)
    .aspect(aspect('ordo') * 5)
    .register()
