package materials

import gregtech.api.fluids.FluidBuilder
import gregtech.api.fluids.attribute.FluidAttributes
import gregtech.api.unification.material.Material
import gregtech.api.unification.material.properties.BlastProperty.GasTier
import gregtech.api.unification.material.properties.PropertyKey
import gregtech.api.unification.material.properties.ToolProperty
import gregtech.api.unification.material.info.MaterialIconSet

import static gregtech.api.GTValues.*
import static gregtech.api.unification.material.Materials.*
import static gregtech.api.unification.material.info.MaterialFlags.*
import static gregtech.api.util.GTUtility.gregtechId

import net.minecraft.init.Enchantments

import material.GTHHMaterialIconSet

import static materials.GTHHMaterials.*


class GTHHFirstDegreeMaterials {

    static void register() {

    }

}
