recipemap('gthh_blast_recipes').recipeBuilder()
    .inputs(metaitem('dustCryolite') * 10, metaitem('dustAluminium') * 2)
    .outputs(metaitem('ingotAluminium') * 3)
    .property("temperature", 933.45)
    .duration(2652)
    .EUt(120)
    .buildAndRegister()