// Aluminium Ingot * 1
mods.gregtech.gthh_blast_recipes.removeByInput(120, [metaitem('dustAluminium'), metaitem('circuit.integrated').withNbt(['Configuration': 1])], null)
mods.gregtech.gthh_blast_recipes.removeByInput(120, [metaitem('dustAluminium'), metaitem('circuit.integrated').withNbt(['Configuration': 2])], [fluid('nitrogen') * 1000 * 1000])

recipemap('compressor').recipeBuilder()
    .inputs(metaitem('dustAluminium') * 1)
    .outputs(metaitem('raw.aluminium') * 1)
    .duration(200)
    .EUt(2)
    .buildAndRegister()

recipemap('gthh_blast_recipes').recipeBuilder()
    .inputs(metaitem('raw.aluminium') * 1)
    .outputs(metaitem('ingotAluminium') * 1)
    .circuitMeta(1)
    .property("temperature", 933.45)
    .duration(884)
    .EUt(120)
    .buildAndRegister()

recipemap('gthh_blast_recipes').recipeBuilder()
    .inputs(metaitem('raw.aluminium') * 1)
    .outputs(metaitem('ingotAluminium') * 1)
    .fluidInputs(fluid('nitrogen') * 1000)
    .circuitMeta(2)
    .property("temperature", 933.45)
    .duration(592)
    .EUt(120)
    .buildAndRegister()

recipemap('gthh_blast_recipes').recipeBuilder()
    .inputs(metaitem('dustAluminium') * 1)
    .outputs(metaitem('ingotAluminium') * 1)
    .circuitMeta(1)
    .property("temperature", 933.45)
    .duration(884)
    .EUt(1920)
    .buildAndRegister()

recipemap('gthh_blast_recipes').recipeBuilder()
    .inputs(metaitem('dustAluminium') * 1)
    .outputs(metaitem('ingotAluminium') * 1)
    .fluidInputs(fluid('nitrogen') * 1000)
    .circuitMeta(2)
    .property("temperature", 933.45)
    .duration(592)
    .EUt(1920)
    .buildAndRegister()

recipemap('gthh_blast_recipes').recipeBuilder()
    .inputs(metaitem('dustCryolite') * 10, metaitem('dustAluminium') * 2)
    .outputs(metaitem('ingotAluminium') * 3)
    .property("temperature", 933.45)
    .duration(2652)
    .EUt(120)
    .buildAndRegister()