// Gallium Arsenide Dust * 2
mods.gregtech.mixer.removeByInput(7, [metaitem('dustGallium'), metaitem('dustArsenic'), metaitem('circuit.integrated').withNbt(['Configuration': 1])], null)

recipemap('gthh_blast_recipes').recipeBuilder()
    .inputs(metaitem('dustGallium') * 1, metaitem('dustArsenic') * 1)
    .outputs(metaitem('raw.gallium_arsenide') * 1)
    .circuitMeta(1)
    .blastFurnaceTemp(1400)
    .duration(1452)
    .EUt(96)
    .buildAndRegister()

recipemap('gthh_blast_recipes').recipeBuilder()
    .inputs(metaitem('dustGallium') * 1, metaitem('dustArsenic') * 1)
    .outputs(metaitem('raw.gallium_arsenide') * 1)
    .fluidInputs(fluid('nitrogen') * 1000)
    .circuitMeta(2)
    .blastFurnaceTemp(1400)
    .duration(855)
    .EUt(96)
    .buildAndRegister()

recipemap('macerator').recipeBuilder()
    .inputs(metaitem('raw.gallium_arsenide') * 1)
    .outputs(metaitem('dustGalliumArsenide') * 2)
    .duration(200)
    .EUt(2)
    .buildAndRegister()