recipemap('chemical_reactor').recipeBuilder()
    .inputs(ore('dustSilicon') * 1)
    .outputs(metaitem('dustSiliconDioxide') * 3)
    .circuitMeta(1)
    .fluidInputs(fluid('oxygen') * 2000)
    .duration(100)
    .EUt(30)
    .buildAndRegister()

recipemap('chemical_reactor').recipeBuilder()
    .inputs(ore('dustSiliconDioxide') * 3, ore('dustMagnesium') * 2)
    .outputs(metaitem('dustSolarGradeSilicon') * 1, metaitem('dustMagnesia') * 4)
    .circuitMeta(1)
    .duration(200)
    .EUt(30)
    .buildAndRegister()