recipemap('mixer').recipeBuilder()
    .inputs(ore('dustSteel') * 1, ore('dustSilicon') * 1)
    .outputs(metaitem('dustElectricalSteel') * 2)
    .circuitMeta(5)
    .duration(600)
    .EUt(24)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustGold') * 1, ore('dustRedstone') * 1, ore('dustGlowstone') * 1)
    .outputs(metaitem('dustEnergeticAlloy') * 3)
    .circuitMeta(5)
    .duration(600)
    .EUt(24)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustEnergeticAlloy') * 1, ore('dustEnderPearl') * 1)
    .outputs(metaitem('dustVibrantAlloy') * 2)
    .circuitMeta(5)
    .duration(600)
    .EUt(96)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustElectricalSteel') * 4, ore('dustRedstone') * 1, ore('dustSilicon') * 1)
    .outputs(metaitem('dustRedstoneAlloy') * 6)
    .circuitMeta(5)
    .duration(600)
    .EUt(24)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustRedstoneAlloy') * 4, ore('dustSteel') * 1, ore('dustRedstone') * 1)
    .outputs(metaitem('dustConductiveIron') * 6)
    .circuitMeta(5)
    .duration(600)
    .EUt(24)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustSteel') * 1, ore('dustEnderPearl') * 1)
    .outputs(metaitem('dustPulsatingIron') * 2)
    .circuitMeta(5)
    .duration(600)
    .EUt(24)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustSteel') * 1, ore('dustObsidian') * 1)
    .outputs(metaitem('dustDarkSteel') * 2)
    .circuitMeta(5)
    .duration(600)
    .EUt(24)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustElectrum') * 1, ore('soulSand') * 1)
    .outputs(item('enderio:item_material', 74) * 2)
    .circuitMeta(5)
    .duration(600)
    .EUt(24)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustDarkSteel') * 1, ore('dustEndstone') * 1)
    .outputs(metaitem('dustEndSteel') * 2)
    .circuitMeta(5)
    .duration(600)
    .EUt(24)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustClay') * 1, ore('dustStone') * 1, ore('gravel') * 1)
    .outputs(metaitem('dustCrudeSteel') * 3)
    .duration(600)
    .EUt(8)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustVibrantAlloy') * 1, ore('itemPulsatingPowder') * 1)
    .outputs(metaitem('dustCrystallineAlloy') * 2)
    .circuitMeta(5)
    .duration(600)
    .EUt(480)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustVibrantAlloy') * 1, item('minecraft:chorus_fruit_popped') * 1)
    .outputs(metaitem('dustMelodicAlloy') * 2)
    .circuitMeta(5)
    .duration(600)
    .EUt(120)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustVibrantAlloy') * 1, ore('dustMelodicAlloy') * 1, ore('dustEndSteel') * 1, ore('dustCrystallineAlloy') * 1)
    .outputs(metaitem('dustCrystallinePinkSlime') * 4)
    .circuitMeta(5)
    .duration(600)
    .EUt(480)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustSilver') * 1, ore('dustRedstone') * 1, ore('dustGlowstone') * 1)
    .outputs(metaitem('dustEnergeticSilver') * 3)
    .circuitMeta(5)
    .duration(600)
    .EUt(30)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustEnergeticSilver') * 1, ore('dustEnderPearl') * 1)
    .outputs(metaitem('dustVividAlloy') * 2)
    .circuitMeta(5)
    .duration(600)
    .EUt(120)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustVividAlloy') * 1, ore('dustVibrantAlloy') * 1, ore('dustEndSteel') * 1, ore('dustConductiveIron') * 1, ore('dustNaquadahAlloy') * 1, ore('dustCrystallinePinkSlime') * 6)
    .circuitMeta(5)
    .outputs(metaitem('dustStellarAlloy') * 11)
    .duration(600)
    .EUt(1920)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('itemVibrantPowder') * 2, ore('itemPulsatingPowder') * 2, ore('itemEnderCrystalPowder') * 1)
    .circuitMeta(5)
    .outputs(metaitem('dustWeatherCrystal') * 5)
    .duration(500)
    .EUt(96)
    .buildAndRegister()

recipemap('mixer').recipeBuilder()
    .inputs(ore('dustStone') * 1, ore('dustQuartzSand') * 1, ore('dustClay') * 1, ore('dustSilicon') * 1)
    .circuitMeta(1)
    .outputs(metaitem('dustSandCompound') * 4)
    .duration(500)
    .EUt(64)
    .buildAndRegister()
